version: '3.8'

services:
  backend:
    build:
      context: .
      target: development  # Altere para 'production' em ambiente real
    ports:
      - '3000:3000'
      - '9229:9229'  # Porta para debug
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://demeters:demeters@postgres:5432/demeters?schema=public
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Evita sobrescrita pelo host
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-demeters}
      POSTGRES_USER: ${POSTGRES_USER:-demeters}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-demeters}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER:-demeters} -d $${POSTGRES_DB:-demeters}']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: